version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: on-failure # What to do if container crashes
    stdin_open: true
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: on-failure
    links:
      - database # link this service to the database service
  database: # name of the third service
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment: 
      MONGO_INITDB_DATABASE: records
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
